<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createTestFromCapturedPipelineData</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIHNlcnZpY2VOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZS5nZXRDdXJz
b3IoKSwgInNlcnZpY2VOYW1lIik7DQpTdHJpbmcgcGFja2FnZU5hbWUgPSBJRGF0YVV0aWwuZ2V0
U3RyaW5nKHBpcGVsaW5lLmdldEN1cnNvcigpLCAicGFja2FnZU5hbWUiKTsNCmJvb2xlYW4gcmVt
b3ZlUGlwZWxpbmVEYXRhID0gSURhdGFVdGlsLmdldEJvb2xlYW4ocGlwZWxpbmUuZ2V0Q3Vyc29y
KCksICJyZW1vdmVQaXBlbGluZURhdGEiLCBmYWxzZSk7DQpTdHJpbmcgdGVzdFN1aXRlTmFtZVBy
ZWZpeCA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmUuZ2V0Q3Vyc29yKCksICJ0ZXN0U3Vp
dGVOYW1lUHJlZml4Iik7DQogIA0KY29tLnNhZy53eC5pcy5yZWdyZXNzaW9udG9vbHMudGVzdGJ1
aWxkZXIuVGVzdENhc2VCdWlsZGVyIGJ1aWxkZXIgPSBuZXcgY29tLnNhZy53eC5pcy5yZWdyZXNz
aW9udG9vbHMudGVzdGJ1aWxkZXIuVGVzdENhc2VCdWlsZGVyKCk7DQp0cnkgew0KYnVpbGRlci5j
cmVhdGVUZXN0Q2FzZXNGb3JTZXJ2aWNlKHNlcnZpY2VOYW1lLCBwYWNrYWdlTmFtZSwgcmVtb3Zl
UGlwZWxpbmVEYXRhLCB0ZXN0U3VpdGVOYW1lUHJlZml4KTsNCn0gY2F0Y2goRXhjZXB0aW9uIGUp
IHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiQ291bGQgbm90IGNyZWF0ZSB0ZXN0IGNh
c2VzOiAiICsgZSk7IA0KfQ==</value>
</Values>
