<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getServerDetails</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNClN0cmluZyBmaWxlU2VwYXJhdG9yID0gU3lzdGVtLmdldFByb3BlcnR5KCJm
aWxlLnNlcGFyYXRvciIpOw0KLy8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29y
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwg
Imhvc3QiLCBTZXJ2ZXJBUEkuZ2V0U2VydmVyTmFtZSgpICk7DQpJRGF0YVV0aWwucHV0KCBwaXBl
bGluZUN1cnNvciwgInBvcnQiLCBTZXJ2ZXJBUEkuZ2V0Q3VycmVudFBvcnQoKSsiIiApOw0KDQpJ
RGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwgInJlc291cmNlc0RpciIsIChTZXJ2ZXJBUEku
Z2V0UGFja2FnZUNvbmZpZ0RpcigiV3hSZWdyZXNzaW9uVG9vbHMiKSkuZ2V0QWJzb2x1dGVQYXRo
KCkuc3Vic3RyaW5nKDAsIChTZXJ2ZXJBUEkuZ2V0UGFja2FnZUNvbmZpZ0RpcigiV3hSZWdyZXNz
aW9uVG9vbHMiKSkuDQoJCWdldEFic29sdXRlUGF0aCgpLmxhc3RJbmRleE9mKCJjb25maWciKSkr
InJlc291cmNlcyIrZmlsZVNlcGFyYXRvciApOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJz
b3IsICJwaXBlbGluZURpciIsIFNlcnZlckFQSS5nZXRTZXJ2ZXJDb25maWdEaXIoKS5nZXRBYnNv
bHV0ZVBhdGgoKS4NCgkJc3Vic3RyaW5nKDAsU2VydmVyQVBJLmdldFNlcnZlckNvbmZpZ0Rpcigp
LmdldEFic29sdXRlUGF0aCgpLmxhc3RJbmRleE9mKCJjb25maWciKSkrInBpcGVsaW5lIitmaWxl
U2VwYXJhdG9yDQoJCSk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7IA0KCQ==</value>
</Values>
