<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeContentToFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlmaWxlTG9jYXRpb24gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImZp
bGVMb2NhdGlvbiIgKTsNClN0cmluZyBmaWxlQ29udGVudCA9ICIiOw0KU3RyaW5nIHN0YXR1cyA9
ICJTVUNDRVNTIjsNCmlmKElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiZmls
ZUNvbnRlbnQiICkgIT0gbnVsbCkNCglmaWxlQ29udGVudCA9IElEYXRhVXRpbC5nZXRTdHJpbmco
IHBpcGVsaW5lQ3Vyc29yLCAiZmlsZUNvbnRlbnQiICk7DQp0cnkgew0KCSBGaWxlVXRpbHMud3Jp
dGVTdHJpbmdUb0ZpbGUobmV3IEZpbGUoZmlsZUxvY2F0aW9uKSwgZmlsZUNvbnRlbnQpOw0KfSBj
YXRjaCAoSU9FeGNlcHRpb24gZSkgew0KCS8vIFRPRE8gQXV0by1nZW5lcmF0ZWQgY2F0Y2ggYmxv
Y2sNCgllLnByaW50U3RhY2tUcmFjZSgpOw0KCXN0YXR1cyA9ICJGQUlMRUQiICsgZS5nZXRNZXNz
YWdlKCk7DQp9DQovLyBwaXBlbGluZQ0KDQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwg
InN0YXR1cyIsIHN0YXR1cyApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
