<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">serviceNameGenerator</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yPXBpcGVsaW5lLmdldEN1cnNvcigpOw0KU3RyaW5nW10gaXBzPUlE
YXRhVXRpbC5nZXRTdHJpbmdBcnJheShjdXJzb3IsICJzZXJ2aWNlTmFtZXMiKTsNCkFycmF5TGlz
dCA8U3RyaW5nPiBzZXJ2aWNlcyA9IG5ldyBBcnJheUxpc3Q8U3RyaW5nPigpOw0KDQpmb3IgKFN0
cmluZyBpbnB1dDogaXBzKXsNCglTdHJpbmcgdGVtcCA9IGlucHV0LnN1YnN0cmluZygwLGlucHV0
Lmxhc3RJbmRleE9mKCJfIikpOw0KCXRlbXAgPSB0ZW1wLnJlcGxhY2UoIl8iLCAiLiIpOw0KCXRl
bXAgPSB0ZW1wKyI6IitpbnB1dC5zdWJzdHJpbmcoaW5wdXQubGFzdEluZGV4T2YoIl8iKSsxKTsN
CgkNCgkNCglzZXJ2aWNlcy5hZGQodGVtcCk7DQp9DQoNCmlmKHNlcnZpY2VzLnNpemUoKT4wKQ0K
CUlEYXRhVXRpbC5wdXQoY3Vyc29yLCAic2VydmljZU5hbWVPdXQiLCBzZXJ2aWNlcy50b0FycmF5
KG5ldyBTdHJpbmdbc2VydmljZXMuc2l6ZSgpXSkpOw0KDQoJ</value>
</Values>
