<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removePipelineFiles</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCXNlcnZpY2UgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgInNlcnZpY2UiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQpTdHJpbmcgcGlw
ZWxpbmVEaXIgPSBTZXJ2ZXJBUEkuZ2V0U2VydmVyQ29uZmlnRGlyKCkuZ2V0QWJzb2x1dGVQYXRo
KCkuc3Vic3RyaW5nKDAsDQoJCVNlcnZlckFQSS5nZXRTZXJ2ZXJDb25maWdEaXIoKS5nZXRBYnNv
bHV0ZVBhdGgoKS5pbmRleE9mKCJjb25maWciKSkrDQoJCVN5c3RlbS5nZXRQcm9wZXJ0eSgiZmls
ZS5zZXBhcmF0b3IiKSsicGlwZWxpbmUiOyANCkZpbGUgZGlyID0gbmV3IEZpbGUocGlwZWxpbmVE
aXIpOw0KRmlsZUZpbHRlciBmaWxlRmlsdGVyID0gbmV3IFdpbGRjYXJkRmlsZUZpbHRlcihzZXJ2
aWNlLnJlcGxhY2VBbGwoIjoiLCAiXyIpKyIqLnhtbCIpOw0KRmlsZVtdIGZpbGVzID0gZGlyLmxp
c3RGaWxlcyhmaWxlRmlsdGVyKTsNCmZvciAoaW50IGkgPSAwOyBpIDwgZmlsZXMubGVuZ3RoOyBp
KyspIHsNCiAgIC8vU3lzdGVtLm91dC5wcmludGxuKGZpbGVzW2ldKTsNCiAgIEZpbGVVdGlscy5k
ZWxldGVRdWlldGx5KGZpbGVzW2ldKTsNCn0NCg0KLy8gcGlwZWxpbmUNCgk=</value>
</Values>
